name: murel_GCN1_knn_unroll_NLLLoss
checkpoint_option: fresh #can be 'best' or 'fresh' or 'resume_last'
ROOT_DIR: '/auto/homes/bat34/VQA_PartII/murel'
bottom_up_features_dir: '/auto/homes/bat34/2018-04-27_bottom-up-attention_fixed_36/'
skipthoughts_dir: '/auto/homes/bat34/VQA_PartII/data/skipthoughts'
processed_dir: '/auto/homes/bat34/VQA_PartII/data/processed_splits'
vqa_dir: '/auto/homes/bat34/VQA'
txt_enc: "BayesianUniSkip"
pooling_agg: 'max'
pairwise_agg: 'max' #Remember to change fusion's pairwise_agg too
RESULTS_FILE_PATH: '/auto/homes/bat34/VQA_PartII/murel/murel_graph_knn_NLLLoss_val2014-temp_results.json'
loss_function: 'NLLLoss' # can be soft_cross_entropy or NLLLoss, remember to change RESULTS_FILE_PATH
batch_size: 256
reduction_factor: 8
grad_clip: 0.25
lr: 0.00005
gradual_warmup_steps: [1.0, 4.0, 7.0] #torch.linspace
lr_decay_epochs: [14, 24, 2] #range
lr_decay_rate: .25
epochs: 25
checkpoint_every: 1
num_workers: 12
load_last_epoch: True
unroll_steps: 3
log_every: 50
seed: 1337
fusion_type: block
use_graph_module: True
use_pairwise: False
graph:
    input_dim: 2048
    output_dim: 2048
q_att:
    linear0:
        input_dim: 2400
        output_dim: 512
    linear1: 
        input_dim: 512
        output_dim: 2
fusion:
    pairwise_agg: 'max' 
    graph_fusion:
        type: block
        input_dims: [2048, 2048]
        output_dims: 2048
        dropout_prelin: 0.
        dropout_input: 0.
        chunks: 5
        rank: 5
        mm_dim: 200
    obj_features_question:
        type: block
        input_dims: [4800, 2048]
        output_dims: 2048
        dropout_prelin: 0.
        dropout_input: 0.1
        chunks: 20
        rank: 15
        mm_dim: 1000
    box:
        type: block
        input_dims: [4, 4]
        output_dims: 2048
        dropout_prelin: 0.
        dropout_input: 0.
        chunks: 5
        rank: 5
        mm_dim: 200
    obj_features_obj_features:
        type: block
        input_dims: [2048, 2048]
        output_dims: 2048
        dropout_prelin: 0.
        dropout_input: 0.
        chunks: 5
        rank: 5
        mm_dim: 200
    final_fusion:
        type: block
        input_dims: [4800, 2048]
        output_dims: 3000
        dropout_prelin: 0.1
        dropout_input: 0.
        chunks: 20
        rank: 10
        mm_dim: 1600
