fusion_options:
    dropout: 0.25
    txt_enc: "BayesianUniSkip"
    batch_size: 1024
    lr: 0.0001
    weight_decay: 0
    max_depth: 3
    min_depth: 3
    epochs: 15
    checkpoint_every: 5
    num_workers: 16
    load_last_epoch: Yes
    fusion:
        fusion_type: mutan
        input_fusion_dims: [2048, 2400]
        output_fusion_dims: 3000
        dropout: 0.25