baseline_options:
    dropout: 0.5
    txt_enc: "BayesianUniSkip"
    batch_size: 64
    lr: 0.0001
    weight_decay: 0
    max_depth: 1
    min_depth: 1
    epochs: 5
    checkpoint_every: 1
    
    